[tools]
node = "lts"
pnpm = "latest"
bun = "latest"
deno = "latest"
"npm:wrangler" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:@biznetgio/cli" = "latest"
"npm:opencode-ai" = "latest"
"npm:openportal" = "latest"

python = "3.14"
uv = "latest"

cargo-binstall = "latest"
"npm:eas-cli" = "latest"


[settings]
experimental = true
disable_backends = ["asdf"]

[settings.npm]
package_manager = "bun"
